data: './data_AAPD/save_data/'
label_dict_file: 'data_AAPD/topic_sorted.json'
logF: 'exp_AAPD/'
epoch: 10
batch_size: 8
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
learning_rate: 0.00002
max_grad_norm: 10
learning_rate_decay: 0.5
start_decay_at: 2
emb_size: 256
encoder_hidden_size: 768
decoder_hidden_size: 768
enc_num_layers: 2
dec_num_layers: 1
bidirectional: True
dropout: 0.1
max_time_step: 30
eval_interval: 100
save_interval: 5000
unk: False
schedule: False
schesamp: False
length_norm: True
metrics: ['micro_f1', 'hamming_loss']
shared_vocab: False
train_beam_size: 1
predict_beam_size: 9
mask: True
global_emb: True
tau: 0.1